version: '3'

services:
  mssql:
    image: microsoft/mssql-server-linux:latest
    ports:
      - 1433:1433
    volumes:
      - mssql_data:/var/opt/mssql
    environment:
      - MSSQL_SA_PASSWORD=no@Password
      - ACCEPT_EULA=Y

  composer:
    image: composer:1.6
    working_dir: /srv/www
    volumes:
      - .:/srv/www
    command: install

  ubuntu:
    depends_on:
      - composer
      - mysql
    build:
      context: docker
      dockerfile: php.Dockerfile
    volumes:
      - .:/var/www

volumes:
  mssql_data:
